apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  name: solar-system
  namespace: solar-system-dev
spec:
    rules:
    - host: solar-system-solar-system-dev.192.168.24.132.nip.io
      http:
        paths:
        - backend:
            service:
              name: solar-system
              port:
                number: 3000
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - solar-system-solar-system-dev.192.168.24.132.nip.io
      secretName: ingress-local-tls