name: Deployment - Reusable Workflow with ArgoCD

on:
  workflow_call:
    inputs:
      MONGO_URI:
        required: true
        type: string
      k8s-manifests-directory:
        description: provide the directory where k8s manifests are stored
        default: kubernetes/
        required: true
        type: string
      environment:
        description: provide the Deployment Environment name
        default: development
        required: true
        type: string
      argocd-app-name:
        description: Name of the ArgoCD Application resource
        required: true
        type: string
      git-repo-url:
        description: URL of the Git repository containing manifests
        required: true
        type: string
      git-revision:
        description: Git revision (branch/tag/commit) to deploy
        default: main
        required: true
        type: string
    secrets:
      ARGOCD_TOKEN:
        required: true
      MONGO_PASSWORD:
        required: true
    outputs:
      APP_INGRESS_URL:
        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}

jobs:
  reuse-deploy:
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # # Install ArgoCD CLI
      # - name: Install ArgoCD CLI
      #   run: |
      #     curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      #     sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      #     rm argocd-linux-amd64

      # Login to ArgoCD
      - name: Login to ArgoCD
        run: |
          argocd login ${{ vars.ARGOCD_SERVER }} \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      # Create MongoDB Secret (if not using external secrets)
      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ inputs.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -

      # Create or sync ArgoCD Application
      - name: Deploy using ArgoCD
        run: |
          # Check if application exists
          if ! argocd app get ${{ inputs.argocd-app-name }}; then
            # Create new application
            argocd app create ${{ inputs.argocd-app-name }} \
              --repo ${{ inputs.git-repo-url }} \
              --path ${{ inputs.k8s-manifests-directory }} \
              --dest-server https://kubernetes.default.svc \
              --dest-namespace ${{ vars.NAMESPACE }} \
              --revision ${{ inputs.git-revision }} \
              --sync-policy automated \
              --auto-prune \
              --self-heal
          else
            # Update existing application
            argocd app set ${{ inputs.argocd-app-name }} \
              --repo ${{ inputs.git-repo-url }} \
              --path ${{ inputs.k8s-manifests-directory }} \
              --revision ${{ inputs.git-revision }}
            
            # Sync the application
            argocd app sync ${{ inputs.argocd-app-name }} \
              --prune \
              --force
          fi

          # Wait for synchronization
          argocd app wait ${{ inputs.argocd-app-name }} --health

      - name: Set App Ingress Host URL
        id: set-ingress-host-address
        run: |
          APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress solar-system -o jsonpath='{.spec.rules[0].host}')
          echo "APP_INGRESS_HOST=$APP_INGRESS_HOST" >> $GITHUB_OUTPUT
