name: Deployment - Reusable Workflow with ArgoCD

on:
  workflow_call:
    inputs:
      MONGO_URI:
        required: true
        type: string
      k8s-manifests-directory:
        default: kubernetes/
        required: true
        type: string
      environment:
        default: development
        required: true
        type: string
      argocd-app-name:
        required: true
        type: string
      git-repo-url:
        required: true
        type: string
      git-revision:
        default: main
        required: true
        type: string
    secrets:
      ARGOCD_TOKEN:
        required: true
      ARGOCD_SERVER:
        required: true
      ARGOCD_PASSWORD:
        required: true
      MONGO_PASSWORD:
        required: true
    outputs:
      APP_INGRESS_URL:
        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}

jobs:
  reuse-deploy:
    runs-on: [self-hosted, linux, X64]
    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set up Git identity
    - name: Setup Git Identity
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    # Get Ingress IP (optional)
    - name: Get Ingress IP
      id: ingress-ip
      run: |
        INGRESS_IP=$(kubectl get svc traefik -n kube-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV

    # Replace placeholders in manifests
    - name: Update Kubernetes Manifests with New Image Tag
      run: |
        find ${{ inputs.k8s-manifests-directory }} -name '*.yaml' -exec sed -i \
          -e "s|_{_NAMESPACE_}_|${{ inputs.environment }}|g" \
          -e "s|_{_IMAGE_}_|${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}|g" \
          -e "s|_{_INGRESS_IP_}_|${{ env.INGRESS_IP }}|g" \
          -e "s|\${GIT_SHA}|${{ github.sha }}|g" \
          {} \;

        echo "Modified manifests:"
        cat ${{ inputs.k8s-manifests-directory }}/*.yaml

    # Commit & Push the modified manifests
    - name: Commit and Push Manifest Changes
      run: |
        git add ${{ inputs.k8s-manifests-directory }}
        git commit -m "ci: update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push origin HEAD:${{ inputs.git-revision }}

    # # Optional: Trigger ArgoCD sync manually (if auto-sync is disabled)
    # - name: Sync ArgoCD Application
    #   run: |
    #     argocd login ${{ secrets.ARGOCD_SERVER }} \
    #       --username admin \
    #       --password ${{ secrets.ARGOCD_PASSWORD }} \
    #       --insecure

    #     argocd app sync ${{ inputs.argocd-app-name }} --prune --force
    #     argocd app wait ${{ inputs.argocd-app-name }} --health || true
    #     argocd app get ${{ inputs.argocd-app-name }}

    # Output the ingress hostname
    - name: Set App Ingress Host URL
      id: set-ingress-host-address
      run: |
        sleep 10
        APP_INGRESS_HOST=$(kubectl -n ${{ inputs.environment }} get ingress solar-system -o jsonpath='{.spec.rules[0].host}')
        echo "APP_INGRESS_HOST=$APP_INGRESS_HOST" >> $GITHUB_OUTPUT
        echo "Ingress URL: https://$APP_INGRESS_HOST"
