name: Deployment - Reusable Workflow

on:
  workflow_call:

jobs:
  reuse-deploy:
    environment:
      name: development
      url: https://${{ env.APP_INGRESS_HOST }}
    outputs:
      APP_INGRESS_URL: ${{ env.APP_INGRESS_HOST }}
    runs-on: [self-hosted, linux, prod]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl version
          kubectl get nodes

      - name: Ensure Namespace Exists
        run: kubectl create namespace ${{ vars.NAMESPACE }} || true

      - name: Set Ingress IP
        run: |
          export INGRESS_IP=$(kubectl get service traefik -n kube-system -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV

      - name: Replace Tokens in Manifests
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f kubernetes/development

      - name: Set Ingress Host
        id: ingress-host
        run: |
          APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress solar-system -o jsonpath='{.spec.rules[0].host}')
          echo "APP_INGRESS_HOST=$APP_INGRESS_HOST" >> $GITHUB_ENV
