name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  NODE_OPTIONS: --no-deprecation

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs_version }}

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test | tee test-results-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}.xml

    - name: Ensure Test Results Directory Exists
      run: mkdir -p test-results

    - name: Move Test Results
      run: mv test-results-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}.xml test-results/

    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Mocha-Test-Result-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}-${{ github.run_id }}
        path: test-results/
        if-no-files-found: ignore

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: unit-testing  # Ensure this job runs after unit-testing

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS - 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install

    - name: Run Code Coverage
      run: npm run coverage | tee coverage-results.xml

    - name: Ensure Coverage Results Directory Exists
      run: mkdir -p coverage-results

    - name: Move Coverage Results
      run: mv coverage-results.xml coverage-results/

    - name: Archive Coverage Results
      uses: actions/upload-artifact@v4
      with:
        name: Code-Coverage-Result-${{ github.run_id }}
        path: coverage-results/
        retention-days: 1