name: Testing Self-Hosted Runner
on:
  workflow_dispatch:  

jobs:
  testing:
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: Echo Content
        run: |
          echo Ok
          sleep 1500s
